GET http://localhost:3000/

###
GET http://localhost:3000/routes

###
GET http://localhost:3000/routes/1

###
POST http://localhost:3000/routes
Content-Type: application/json

{
  "name": "testing route 1",
  "source_id": "1",
  "destination_id": "2"
}

### Maps stuff ###

### Get place_id
GET http://localhost:3000/places?text=darce_lavras

### Get directions between 2 points
# GET http://localhost:3000/directions?originId=<put_origin_id_here>&destinationId=<put_destination_id_here>
GET http://localhost:3000/directions?originId=ChIJvSKUD4z9nwARrmBuvYI7CTY&destinationId=ChIJ7ZCG_9j9nwARVOLlSsYMvec