version: '3'

services:
  app:
    build: . # This uses the Dockerfile in the current directory to build the image for the app service.
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
